<a href="https://colab.research.google.com/github/calogero308/GPO/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Successivamente vengono importate le principali librerie che verranno usate, principalmente in datascience, con successiva print della versione di pytorch

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


In [6]:
!nvidia-smi

Tue Oct 28 15:38:53 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

PyTorch tensors ovvero vettori multidimensionali su pytorch vengono creati con torch.tensor(), in questo caso di uno scalare. La cosa principale da ricordare è che in pytorch per la rappresentazione numerica vengono sempre utilizzati i **tensors**.

In [14]:
##Introduction to tensors
###Creating tensors
#Scalar

import torch
scalar = torch.tensor(7)
scalar

tensor(7)

Con il comando successivo va a calcolare la dimensione del tensor, in questo caso uno scalare non ha dimensione.

In [11]:
scalar.ndim

0

questa funzione mi da la possibilità di stampare il valore presente dentro la variabile.

In [12]:
#Get tensors back as PyThon int
scalar.item()

7

Adesso creiamo un vettore, la funzione **ndim** ci restituisce lo stesso valore di uno scalare poichè in questo caso abbiamo una sola dimensione nel vettore, Invece la funzione **shape** ci restituisce la dimensione effettiva, ovvero il numero di elementi presenti nel vettore.

In [22]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [20]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

Adesso creiamo una **Matrice**, valgono tutte le funzioni precedenti: ndim, shape

In [24]:
#Matrix
Matrix = torch.tensor([[7, 7],
                       [3, 5]])
Matrix

tensor([[7, 7],
        [3, 5]])

Posso andare a scegliere la dimensione da studiare con le parentesi quadre

In [30]:
Matrix[1]

tensor([7, 7])

In [26]:
Matrix.ndim

2

In [27]:
Matrix.shape

torch.Size([2, 2])

Quello fatto in precedenza può essere modificato per creare tensors con più
 dimensioni: 3, 4, ... e poter applicare tutte le funzioni precedentemente viste sopra

In [31]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [32]:
TENSOR.ndim

3

In [33]:
TENSOR.shape

torch.Size([1, 3, 3])